### ISSUE TITLE
[Improvement] More helpful messages when map code includes unsupported JS APIs

### ISSUE THREAD

**Issue by zdne** [superfaceai/one-sdk#66]
## Expected Behavior
When I use `console.log()` in a comlink map I'd like to know that I am using unsupported JS API. 

## Current Behavior
When I have a map with a JS API that is not supported e.g (`console.log("message")`) I get a very generic error:

```
ERROR: {
 "name": "JsInterpreterError"
}
```

## Possible Solution
Ideally I'd like to know that the JS API function I've used is not supported. At least let me know that something is wrong with the comlink map (and which). 

## Steps to Reproduce
Add `console.log("message")` to any map and execute OneSDK perform.

## Your Environment
- macOS
- OneSDK Beta.0
- node 18.13

**Comment by TheEdward162** [comment]
Can you please share how you are invoking the SDK, and especially how you are handling the error? There should be a stacktrace attached to the error. For example, when I let the error bubble up without catching it I get:
```
...

UnexpectedError [JsInterpreterError]: Code evaluation failed: Uncaught ReferenceError: 'console' is not defined
    at Example (map.js:13)
    at _start (map_std.js:373)
    at <eval> (map.js:52)
    
...
```

**Comment by zdne** [comment]
Per our slack discussion if I add error message explicitly to the error handling then I can see it:

```
catch (e) {
    console.log("ERROR:", JSON.stringify(e, null, 2));
    console.log("message:", e.message);
  }
}
```

Would it be possible to have the message serialized with `JSON.stringify(e, null, 2)` ? Or we need to fix it on the side of error handling?

**Comment by TheEdward162** [comment]
I think this is mostly a documentation issue, as there are two main classes of errors (`UnexpectedError` and `PerformError`) and they should be handled differently.

Nevertheless, I've create a PR which improves this specific error a little bit, although that has nothing to do with the JSON serialization.

I will also add logging of unexpected errors into the user log for visibility.
